<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Stock Movement Report - {{ now()->format('Y-m-d') }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
            font-family: 'Segoe UI', Arial, sans-serif; 
            font-size: 11px; 
            line-height: 1.4;
            color: #1e293b;
            padding: 20px;
        }
        .header { 
            text-align: center; 
            margin-bottom: 30px; 
            padding-bottom: 15px; 
            border-bottom: 3px solid #0b1a68; 
        }
        .header h1 { 
            color: #0b1a68; 
            font-size: 26px; 
            margin-bottom: 8px;
            font-weight: 700;
        }
        .header h2 { 
            color: #334155; 
            font-size: 18px; 
            margin-bottom: 12px;
            font-weight: 600;
        }
        .header .meta { 
            color: #64748b; 
            font-size: 10px;
            line-height: 1.6;
        }
        .filters-applied {
            background: #f1f5f9;
            padding: 12px;
            border-radius: 6px;
            margin-bottom: 20px;
            border-left: 4px solid #0b1a68;
        }
        .filters-applied strong {
            color: #0b1a68;
            font-size: 11px;
        }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-bottom: 20px;
            background: white;
        }
        thead { 
            background: #0b1a68; 
            color: white;
        }
        th { 
            padding: 10px 8px; 
            text-align: left; 
            font-weight: 600; 
            font-size: 10px; 
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        td { 
            padding: 9px 8px; 
            border-bottom: 1px solid #e2e8f0; 
            font-size: 10px;
        }
        tbody tr:nth-child(even) { 
            background: #f8fafc; 
        }
        tbody tr:hover { 
            background: #f1f5f9; 
        }
        .badge { 
            padding: 3px 8px; 
            border-radius: 12px; 
            font-size: 9px; 
            font-weight: 600; 
            display: inline-block;
            white-space: nowrap;
        }
        .badge-incoming { background: #d1fae5; color: #065f46; }
        .badge-issued { background: #fef3c7; color: #92400e; }
        .badge-returned { background: #dbeafe; color: #1e40af; }
        .badge-transfer { background: #dbeafe; color: #1e40af; }
        .badge-pending { background: #fef3c7; color: #92400e; }
        .badge-approved { background: #d1fae5; color: #065f46; }
        .qty-positive { color: #059669; font-weight: 600; }
        .qty-negative { color: #dc2626; font-weight: 600; }
        .footer { 
            text-align: center; 
            margin-top: 30px; 
            padding-top: 15px; 
            border-top: 2px solid #e2e8f0; 
            color: #64748b; 
            font-size: 9px;
        }
        .summary {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
            gap: 15px;
        }
        .summary-card {
            flex: 1;
            background: #f8fafc;
            padding: 12px;
            border-radius: 6px;
            border-left: 4px solid #0b1a68;
        }
        .summary-card h3 {
            font-size: 10px;
            color: #64748b;
            margin-bottom: 4px;
            text-transform: uppercase;
        }
        .summary-card .value {
            font-size: 20px;
            font-weight: 700;
            color: #0b1a68;
        }
        @media print {
            body { padding: 10px; }
            table { page-break-inside: auto; }
            tr { page-break-inside: avoid; page-break-after: auto; }
            thead { display: table-header-group; }
            @page { margin: 1.5cm; }
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>🏢 INFLIGHT CATERING SYSTEM</h1>
        <h2>Stock Movement Report</h2>
        <div class="meta">
            <p><strong>Generated:</strong> {{ $generated_at }}</p>
            <p><strong>Generated By:</strong> {{ $generated_by }}</p>
            <p><strong>Total Records:</strong> {{ $movements->count() }}</p>
        </div>
    </div>

    <!-- Filters Applied -->
    @if($filters['type'] || $filters['product_id'] || $filters['search'])
    <div class="filters-applied">
        <strong>📋 Filters Applied:</strong>
        @if($filters['type'])
            <span style="margin-left: 10px;">Type: <strong>{{ ucfirst(str_replace('_', ' ', $filters['type'])) }}</strong></span>
        @endif
        @if($filters['product_id'])
            <span style="margin-left: 10px;">Product: <strong>{{ $products->find($filters['product_id'])->name ?? 'Unknown' }}</strong></span>
        @endif
        @if($filters['search'])
            <span style="margin-left: 10px;">Search: <strong>{{ $filters['search'] }}</strong></span>
        @endif
    </div>
    @endif

    <!-- Summary Cards -->
    <div class="summary">
        <div class="summary-card">
            <h3>Total Incoming</h3>
            <div class="value">+{{ $movements->where('type', 'incoming')->sum('quantity') }}</div>
        </div>
        <div class="summary-card">
            <h3>Total Issued</h3>
            <div class="value">-{{ $movements->where('type', 'issued')->sum('quantity') }}</div>
        </div>
        <div class="summary-card">
            <h3>Total Transfers</h3>
            <div class="value">-{{ $movements->where('type', 'transfer_to_catering')->sum('quantity') }}</div>
        </div>
        <div class="summary-card">
            <h3>Total Returns</h3>
            <div class="value">+{{ $movements->where('type', 'returned')->sum('quantity') }}</div>
        </div>
    </div>

    <!-- Table -->
    @if($movements->count() > 0)
    <table>
        <thead>
            <tr>
                <th style="width: 10%;">Date</th>
                <th style="width: 12%;">Type</th>
                <th style="width: 20%;">Product</th>
                <th style="width: 8%;">Quantity</th>
                <th style="width: 12%;">Reference</th>
                <th style="width: 10%;">Status</th>
                <th style="width: 13%;">Performed By</th>
                <th style="width: 15%;">Notes</th>
            </tr>
        </thead>
        <tbody>
            @foreach($movements as $movement)
            <tr>
                <td>{{ $movement->movement_date->format('d M Y') }}</td>
                <td>
                    @if($movement->type == 'incoming')
                        <span class="badge badge-incoming">Incoming</span>
                    @elseif($movement->type == 'issued')
                        <span class="badge badge-issued">Issued</span>
                    @elseif($movement->type == 'transfer_to_catering')
                        <span class="badge badge-transfer">Transfer</span>
                    @else
                        <span class="badge badge-returned">Returned</span>
                    @endif
                </td>
                <td>
                    <strong>{{ $movement->product->name }}</strong><br>
                    <small style="color: #94a3b8;">{{ $movement->product->sku }}</small>
                </td>
                <td>
                    @if(in_array($movement->type, ['issued', 'transfer_to_catering']))
                        <span class="qty-negative">-{{ $movement->quantity }}</span>
                    @else
                        <span class="qty-positive">+{{ $movement->quantity }}</span>
                    @endif
                </td>
                <td>{{ $movement->reference_number ?? '-' }}</td>
                <td>
                    @if($movement->status == 'pending')
                        <span class="badge badge-pending">Pending</span>
                    @elseif($movement->status == 'approved')
                        <span class="badge badge-approved">Approved</span>
                    @else
                        <span class="badge badge-approved">Completed</span>
                    @endif
                </td>
                <td>{{ $movement->user->name }}</td>
                <td style="font-size: 9px; color: #64748b;">{{ Str::limit($movement->notes ?? '-', 50) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <div style="text-align: center; padding: 40px; color: #94a3b8;">
        <p>No stock movements found for the selected filters.</p>
    </div>
    @endif

    <!-- Footer -->
    <div class="footer">
        <p>This is an automatically generated report from Inflight Catering System</p>
        <p>© {{ now()->year }} Inflight Catering System. All rights reserved.</p>
    </div>

    <!-- Auto-trigger print dialog -->
    <script>
        window.onload = function() {
            window.print();
        }
    </script>
</body>
</html>
